server:
  servlet:
    context-path:
      /api/minesweeper
  port: 8080
spring:
  datasource:
    initialize: false
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "mysql://ba5907c2889e1f:accadc05@us-cdbr-east-03.cleardb.com/heroku_e8be2e07add90d5?reconnect=true"
    username: ba5907c2889e1f
    password: accadc05
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        connection:
          release_mode: on_close